// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zbcuryjsjkaosxwxrbmf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpiY3VyeWpzamthb3N4d3hyYm1mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwOTMwMjgsImV4cCI6MjA2ODY2OTAyOH0.Az05r5ouYp31oe00N_IYSGE5X_JmoVWMaWrHK9ywLt4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});